### ISSUE TITLE
Seems to be an extra "}" somewhere

### ISSUE THREAD

**Issue by kennedysmartins** [balatamoghna/Whatsapp-Deku#1]
after initializing the project, it returns an error on line 633

```
C:\Server\Deku\WABot.js:633
    else{setTimeout(()=>{counter=0;},15000);}
    ^^^^

SyntaxError: Unexpected token else
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by balatamoghna** [comment]
The issue has been fixed, Thank you for your report!
